@baseUrl = http://js-post-api.herokuapp.com/api

# Students

# @name getAllStudents
GET {{baseUrl}}/students?_page=1&_limit=10

###

# @name getStudentById
GET {{baseUrl}}/students/Y2NYn1S

###

# @name addNewStudent
POST {{baseUrl}}/students
Content-Type: application/json

{
  "name": "Michale Test",
  "age": 27,
  "mark": 9,
  "gender": "male",
  "city": "pt"
}

###

# @name updateStudent
PATCH {{baseUrl}}/students/Y2NYn1S
Content-Type: application/json

{
  "name": "Michale Test",
  "age": 30,
  "mark": 9,
  "gender": "male",
  "city": "pt"
}

###

# @name removeStudent
DELETE  {{baseUrl}}/students/X7BZGIp